language: php

php:
  - 5.6
  - 7.0
  
before_install:
  - composer self-update
  - composer require codeclimate/php-test-reporter --dev
  - phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/test-reporter

